# Generated by Django 5.0.1 on 2024-01-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_cart_session_id_alter_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
