# Generated by Django 4.2.9 on 2024-01-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_cart_stripe_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='success_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
